---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: 12

inputs:
  - name: prod-lakota-ed

caches:
  - path: prod-lakota-ed/node_modules

run:
  path: prod-lakota-ed/ci-cd/lakota-ed/tasks/integration-test-production/run.sh
