resources:
  - name: dev-lakota-ed
    type: git
    source:
      uri: https://github.com/SunilRao01/Lakota-Language-Learning.git
      branch: development

  - name: prod-lakota-ed
    type: git
    source:
      uri: https://github.com/SunilRao01/Lakota-Language-Learning.git
      branch: master

jobs:
  - name: Unit Tests (development)
    plan:
      - aggregate:
          - get: dev-lakota-ed
            trigger: true
      - task: run-unit-tests
        file: dev-lakota-ed/ci-cd/lakota-ed/tasks/unit-test-development/task.yml

  - name: Deploy to QA
    plan:
      - aggregate:
          - get: dev-lakota-ed
            passed:
              - Unit Tests (development)
            trigger: true
      - task: deploy-to-qa
        file: dev-lakota-ed/ci-cd/lakota-ed/tasks/deploy-development/task.yml
        params:
          PRIVATE_RSA_KEY: ((private-rsa-key))
          PUBLIC_RSA_KEY: ((public-rsa-key))
          ENV_STAGING: ((env-staging))

  - name: Integration Tests QA
    plan:
      - aggregate:
          - get: dev-lakota-ed
            passed:
              - Deploy to QA
            trigger: true
      - task: run-integration-tests
        file: dev-lakota-ed/ci-cd/lakota-ed/tasks/integration-test-qa/task.yml

######################################################################################

  - name: Unit Tests (master)
    plan:
      - aggregate:
        - get: prod-lakota-ed
          trigger: true
      - task: run-unit-tests
        file: prod-lakota-ed/ci-cd/lakota-ed/tasks/unit-test-master/task.yml

  - name: Deploy to Production
    plan:
      - aggregate:
          - get: prod-lakota-ed
            trigger: true
            passed:
              - Unit Tests (master)
      - task: deploy-to-production
        file: prod-lakota-ed/ci-cd/lakota-ed/tasks/deploy-production/task.yml
        params:
          PRIVATE_RSA_KEY: ((private-rsa-key))
          PUBLIC_RSA_KEY: ((public-rsa-key))
          ENV_PROD: ((env-prod))

  - name: Integration Tests Production
    plan:
      - aggregate:
          - get: prod-lakota-ed
            passed:
              - Deploy to Production
            trigger: true
      - task: run-integration-tests
        file: prod-lakota-ed/ci-cd/lakota-ed/tasks/integration-test-production/task.yml

groups:
  - name: Development
    jobs:
      - Unit Tests (development)
      - Deploy to QA
      - Integration Tests QA
  - name: Production
    jobs:
      - Unit Tests (master)
      - Deploy to Production
      - Integration Tests Production
