resources:
  - name: dev-lakota-ed
    type: git
    source:
      uri: https://github.com/SunilRao01/Lakota-Language-Learning.git
      branch: development

  - name: prod-lakota-ed
    type: git
    source:
      uri: https://github.com/SunilRao01/Lakota-Language-Learning.git
      branch: master

  - name: dev-server
    type: concourse-ssh-resource
    source:
      hostname: skeletonpraxis.net
      username: root
      private_key: ((private-rsa-key))

jobs:
#  - name: Unit Tests
#    plan:
#      - in_parallel:
#          - get: dev-lakota-ed
#            trigger: true
#      - task: run-unit-tests
#        file: dev-lakota-ed/ci-cd/lakota-ed/tasks/unit-test/task.yml

  - name: Deploy to Dev
    plan:
#      - in_parallel:
#          - get: dev-lakota-ed
##            passed:
##              - Unit Tests
#            trigger: true
      - put: dev-server
        params:
          command: dev-lakota-ed/ci-cd/lakota-ed/tasks/deploy-dev/run.sh

  - name: Integration Tests
    plan:
      - in_parallel:
          - get: dev-lakota-ed
            passed:
              - Deploy to Dev
            trigger: true
      - task: run-integration-tests
        file: dev-lakota-ed/ci-cd/lakota-ed/tasks/integration-test/task.yml

  - name: Deploy to Prod
    plan:
      - in_parallel:
          - get: prod-lakota-ed
            trigger: false
      - task: deploy-to-prod
        file: prod-lakota-ed/ci-cd/lakota-ed/tasks/deploy-prod/task.yml
        params:
          PRIVATE_RSA_KEY: ((private-rsa-key))
          PUBLIC_RSA_KEY: ((public-rsa-key))

groups:
  - name: Development
    jobs:
#      - Unit Tests
      - Deploy to Dev
      - Integration Tests
  - name: Production
    jobs:
      - Deploy to Prod

resource_types:
  - name: concourse-ssh-resource
    type: docker-image
    source:
      repository: edtan1/concourse-ssh-resource
