version: '3'

services:
  api:
    build:
      context: .
    env_file:
      - .dev_env_file
    ports:
      - "4000:4000"
    volumes:
      - './lib:/app/lib'
      - './priv:/app/priv'
      - './config:/app/config'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .db_dev_env_file
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
