---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8.12-jessie

inputs:
  - name: dev-lakota-ed

run:
  path: dev-lakota-ed/ci-cd/lakota-ed/tasks/deploy-dev/run.sh
