---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 20.04

inputs:
  - name: prod-lakota-ed

run:
  path: prod-lakota-ed/ci-cd/lakota-ed/tasks/deploy-api-master/run.sh
