---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 12-stretch

inputs:
  - name: prod-lakota-ed

caches:
  - path: prod-lakota-ed/node_modules

run:
  path: prod-lakota-ed/ci-cd/lakota-ed/tasks/unit-test-master/run.sh
