version: '3.8'

services:
  concourse-db:
    image: postgres
    env_file:
      - db.env

  concourse:
    image: concourse/concourse-rc
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    env_file:
      - concourse.env
    volumes:
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
