version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./db.env
    ports: ["4321:4321"]
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes:
      - ./keys/web:/concourse-keys
      - ~/.ssh:/root/.ssh
    env_file:
      - ./concourse.env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
