version: '3'

services:
  concourse-db:
    image: postgres
    env_file:
      - db.env

  concourse:
    image: concourse/concourse-rc
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    env_file:
      - concourse.env
