version: '3.1'

services:
  concourse-db:
    image: postgres
    env_file:
      - db.env

  concourse:
    image: concourse/concourse-rc
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    env_file:
      - concourse.env
    secrets:
      - private_rsa_key
      - public_rsa_key
    volumes:
      - type: bind
          source: /run/host-services/ssh-auth.sock
          target: /run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock

secrets:
  private_rsa_key:
    file: ~/.ssh/id_rsa
  public_rsa_key:
    file: ~/.ssh/id_rsa.pub
